# Use an official Python runtime as a parent image
FROM python:3.6-slim

# Set the working directory to /app
WORKDIR /FeatureApp

# Copy the current directory contents into the container at /app
COPY . /FeatureApp

# Install any needed packages specified in requirements.txt
RUN pip install --trusted-host pypi.python.org -r requirements.txt
RUN pip install https://github.com/majimboo/py-mathutils/archive/2.78a.zip

# Make port 80 available to the world outside this container
EXPOSE 80

# Define environment variable
ENV NAME World

# Run OptimizeStructure.py when the container launches
CMD ["python", "Features.py"]