# Use an official Python runtime as a parent image
FROM python:3.6-windowsservercore-ltsc2016

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install mathutils-2.78-cp36-cp36m-win_amd64.whl
RUN pip install --trusted-host pypi.python.org -r requirements.txt

# Make port 80 available to the world outside this container
EXPOSE 80

# Define environment variable
ENV NAME World

# Run OptimizeStructure.py when the container launches
CMD ["python", "OptimizeStructure.py"]